services:
  web-test:
    image: nginx:alpine
    container_name: test-web-server
    restart: always
    ports:
      - "8081:80"
    command: >
      /bin/sh -c "echo '<html><body style=\"background:#111;color:#00ff00;font-family:sans-serif;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;\">
      <h1>testing docker compose</h1>
      <p>Status: <span style=\"color:white\">Online</span></p>
      <div style=\"border:1px solid #333;padding:20px;border-radius:10px;\">
        <h3>inside this box, there will be changes underneath: </h3>
        <ul>
          <li>this is the first line asydgfyuwegfyth the postgresdb</li>
          <li>this is the second line abfhsdbfsdhfng with the postgresdb</li>
        </ul>
      </div>
      </body></html>' > /usr/share/nginx/html/index.html && nginx -g \"daemon off;\""
